### ISSUE TITLE
how does it work now

### ISSUE THREAD

**Issue by mapfau** [xbmc/repo-binary-addons#25]
Hi, for now I havent found the inputstream.mpd n the nightly windows build
Also linux apt-cache with nightly ppa enabled doesn't show this addon for installation.

Is something missing in the files supported from me? Some keyword "include me" for example?

**Comment by Montellese** [comment]
I guess for linux PPA someone will have to manually set it up. On Windows we'd have to adjust the installer to also include input stream addons.

But the proper way forward would be to finally get binary addon repositories setup and working. I have already done most of the work needed in the Kodi buildsystem but it needs proper jenkins build configuration and a repository setup on our servers.

**Comment by mapfau** [comment]
this sounds perfect, thanks @Montellese

**Comment by wsnipex** [comment]
as for ubuntu: that packaging files in the addon are broken. At least https://github.com/mapfau/inputstream.mpd/blob/master/debian/control needs some content ;)

Once this is fixed I can add it to the ppa

**Comment by mapfau** [comment]
ok, I'll look if I can find out what should be in this file, thanks!

**Comment by liberty-developer** [comment]
could I copy all files from: https://github.com/FernetMenta/pvr.vdr.vnsi/tree/master/debian
and edit simply the naming inside the files so they match to inputstream.mpd?

To be honest: I don't know any backgrounds about what I'm doing then....

**Comment by mapfau** [comment]
could I copy all files from: https://github.com/FernetMenta/pvr.vdr.vnsi/tree/master/debian
and edit simply the naming inside the files so they match to inputstream.mpd?

To be honest: I don't know any backgrounds about what I'm doing then....

**Comment by mapfau** [comment]
@wsnipex I have completed the file https://github.com/mapfau/inputstream.mpd/blob/master/debian/control as good as I'm able to.
Is it sufficient?

**Comment by mapfau** [comment]
Is there any chance to include the new inputstream addons (kodi.inputstream, kodi.library.inputstream, inpuststream.mpd) into the windows setup file? In setup dialog there should be a new section "InputStream Addons" comparable to "PVR Addons" wich is missing so far.

There are already some folks waiting for it to continue addon development with dash content...

Thanks!

**Comment by Montellese** [comment]
@mapfau: Yeah it sounds perfect but we haven't made any progress in months on this.

**Comment by mapfau** [comment]
@Montellese is there any white paper about the concept available? I just want to get an overview, maybe I can support in in any way....

**Comment by Montellese** [comment]
Not really.
I've adjusted the binary addons system a few months ago to be able to download all binary addon definitions from a repository (by default https://github.com/xbmc/repo-binary-addons) and from an arbitrary branch (by default `master` but that can be changed for specific releases etc.).
With that the buildserver is capable of building binary addons for different releases. What is missing is uploading these builds to a binary addon repository on the server and doing that for all kinds of supported platforms.

One major issue is that our current addons system does not support differing between e.g. android arm and android x86, it only supports android.

**Comment by mapfau** [comment]
@Montellese Just to get it right:
- the binary addon repo could be set up with all differences os types (because the repo is not existing and can be set up as required) and jenkins knows that he has build for x86 and not ARM, is this right?

- The problem exist inside kodi addon system, because kodi is currently not able to catch the right file from the new binary addon repo.

Is this correct?

**Comment by Montellese** [comment]
@mpafau: spot on

**Comment by mapfau** [comment]
@Montellese How should addon installation work from user view?
- Kodi setup (add / remove features)
- Inside kodi application (Settings::Addon::install / remove)

I bet the latter one.....

**Comment by Montellese** [comment]
Yes we want to ship Kodi with the minimal number of binary addons so that the user can freely choose what he needs and what he doesn't.

**Comment by mapfau** [comment]
GUI?

**Comment by wsnipex** [comment]
@mapfau I first have to fixup kodi packaging to include the new headers, then I'll have a look at the addon.

**Comment by mapfau** [comment]
thanx!

**Comment by ace20022** [comment]
@mapfau It seems that the resources dir is missing, c.f. http://mirrors.xbmc.org/test-builds/win32/KodiSetup-20160311-595c1ff-win32_adoonsinstaller.exe

**Comment by mapfau** [comment]
@ace20022 I have just installed the version from the link above - looks fine, Thanks!.
There is a resources dir with an english strings.po file in it. Is there another place where a resources file has to be placed in?

**Comment by mapfau** [comment]
Just recognized that "library.inputstream" is not installed.
As far as I know binary addon libraries are installed regardless what binary addons are selected,

**Comment by fritsch** [comment]
Nope. There is another issue currently. When building system wide it somehow expects the .so files in /usr/share/kodi/addons/inputstream.md/ - which would definitely break multi-arch packaging. I think we have a bug in our AddonDLL loader.

**Comment by MartijnKaijser** [comment]
solved?
